{
 "title": "Мониторинг доставки реальных данных",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Количество срабатываний WatchDog",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(healthcheck_udl_rtdb_subscription_oxygen_watchdog_action_count[5m])"
    }
   ]
  },
  {
   "title": "Реальные данные кислородного цеха",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_oxygen_messages_count[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Реальные данные цеха ТЭЦ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_tec_messages_count[5m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Реальные данные расчетных тегов",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_calculation_messages_count[5m]))",
     "legendFormat": " Value"
    }
   ]
  },
  {
   "title": "Реальные данные Топаз",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_topaz_messages_count[5m]))",
     "legendFormat": " Value"
    }
   ]
  },
  {
   "title": "Реальные данные кислородного цеха",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_oxygen_messages_count[$__interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Общее количество сообщений",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_oxygen_messages_count[$__range]))"
    }
   ]
  },
  {
   "title": "Реальные данные цеха ТЭЦ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_tec_messages_count[$__interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Общее количество сообщений",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_tec_messages_count[$__range]))"
    }
   ]
  },
  {
   "title": "Реальные данные расчетных тегов",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_calculation_messages_count[$__interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Общее количество сообщений",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_calculation_messages_count[$__range]))"
    }
   ]
  },
  {
   "title": "Реальные данные Топаз",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Количество сообщений" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_topaz_messages_count[$__interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Общее количество сообщений",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_topaz_messages_count[$__range]))"
    }
   ]
  }
 ]
}