{
 "title": "Мониторинг доставки реальных данных",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "tplus-0,tplus-1,fosagro" }
  ]
 },
 "panels": [
  { "title": "ТПЛЮС-0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_subscription_status{cluster=\"fosagro\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(idelta(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-0\"}[$__range])) - sum(idelta(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"tplus-0\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Реальные данные проекта ТПЛЮС-0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-0\"}[5m]))"
    }
   ]
  },
  {
   "title": "Общее количество сообщений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-0\"})"
    }
   ]
  },
  {
   "title": "Количество сообщений исключая стартовые",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(idelta(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-0\"}[$__range])) - sum(idelta(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"tplus-0\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Количество ошибок за выбранный период",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"tplus-0\"})"
    }
   ]
  },
  { "title": "ТПЛЮС-1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_subscription_status{cluster=\"fosagro\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(idelta(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-1\"}[$__range])) - sum(idelta(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"tplus-1\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Реальные данные ТПЛЮС-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-1\"}[5m]))"
    }
   ]
  },
  {
   "title": "Общее количество сообщений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-1\"})"
    }
   ]
  },
  {
   "title": "Количество сообщений исключая стартовые",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(idelta(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"tplus-1\"}[$__range])) - sum(idelta(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"tplus-1\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Количество ошибок за выбранный период",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"tplus-1\"})"
    }
   ]
  },
  { "title": "Фосагро", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_subscription_status{cluster=\"fosagro\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(idelta(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"fosagro\"}[$__range])) - sum(idelta(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"fosagro\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Реальные данные проекта Фосагро",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"fosagro\"}[5m]))"
    }
   ]
  },
  {
   "title": "Общее количество сообщений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"fosagro\"})"
    }
   ]
  },
  {
   "title": "Количество сообщений исключая стартовые",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(idelta(healthcheck_udl_rtdb_data_ws_messages_count{cluster=\"fosagro\"}[$__range])) - sum(idelta(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"fosagro\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Количество ошибок за выбранный период",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_udl_rtdb_data_ws_failed_attempts_count{cluster=\"fosagro\"})"
    }
   ]
  }
 ]
}